### ISSUE TITLE
部署到我的vps后，用域名/admin可以进后台，但是用域名访问前台报500

### ISSUE THREAD

**Issue by wumengkang** [qqphp-com/laravel-blog-poetry-all#10]
我的伪静态设置过了，我的nginx配置是这样

server {
    listen       80;
    server_name  www.xxxx.site;
    root   /home/wmk/laravel-blog-poetry-all/code/laravel_blog/public;
    index  index.php index.html index.htm;
   
 location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
   
 error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
  
  location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
  
  location ~ /\.ht {
        deny  all;
    }
}

**Comment by qqphp-com** [comment]
伪静态设置有误。参考一下laravel手册。只需设置那一条即可。打开debug，也有可能是其它配置错误导致。
