### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Wang-xiaozhang** [qqphp-com/laravel-blog-poetry-all#2]
https://qqphp.com/article_details/135
点击后文章内容不显示

**Comment by qqphp-com** [comment]
https://qqphp.com/article_details/135,刷新Pajax不会加载插件，需要文章列表进入才会显示，这个问题目前在修复。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wang-xiaozhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 下午5:20
收件人:&nbsp;"qqphp-com/laravel-blog-poetry-all"<laravel-blog-poetry-all@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qqphp-com/laravel-blog-poetry-all] bug (#2)




https://qqphp.com/article_details/135点击后文章内容不显示
